<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>ls-inventory-api-development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ExcelDataReader" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
    <Content Update="appsettings.Production.json" CopyToPublishDirectory="Never" />
    <Content Include="../../商品信息及现有库存模板.xlsx" Link="Templates/商品信息及现有库存模板.xlsx" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
